# -*- coding: utf-8 -*-
"""Consegna S5/L1_Martina_Albano

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QifBFUouc3VPI4s739QsUaOVO-HOWCkO
"""

#Abbiamo 25 studenti; memorizzare questo dato in una variabile
studenti = 25
print(studenti)

#Arrivano altri 3 studenti; memorizzare questo dato in un'altra variabile
studenti2 = studenti + 3
print(studenti2)

#Creare un'altra variabile ancora che conterrà la somma delle prime due, poi stamparla a video
studenti3= studenti + studenti2
studenti3

#Creare una variabile che contiene la stringa "Epicode", quindi stamparla a video
e = "Epicode"

#Creare, a mano, una lista che contenga i numeri da 0 a 5, memorizzarla in una variabile e infine stamparla a video
lista = [0,1,2,3,4,5]
print(lista)

#Abbiamo la stringa: nome_scuola = "Epicode" Stampare l'iniziale
nome_scuola[-7]

#nome_scuola = "Epicode" Stampare le prime tre lettere
nome_scuola[0]+ nome_scuola[1]+ nome_scuola[2]
'Epi'

#Abbiamo la variabile: x = 10 Incrementarla di 2 e poi moltiplicarla per 3 Usare due metodi diversi (ad esempio, uno utilizzando gli operatori di assegnazione, e uno senza)
x=10
y=2
z=x+y
z*3

parola = input("inserisci una parola!")
print(parola[0:3] + "..." + parola[4:])

#Esercizio Verificare, per ognuna delle seguenti stringhe, se il numero di caratteri è compreso tra 5 e 8:
a = "Windows"
b= "Excel"
c= "Powerpoint"
d= "Word"

#Inventare un programma che prende in input degli elementi e restituisce in output una loro combinazione (ad esempio prendendo in input due numeri e restituendo la loro somma
m=input("inserisci un numero ")
h=input("inserisci un altro numero ")
print( "il risultato dei valori che hai inserito è: " + str(int(m)+int(h)))

if 5 <= len(a) <= 8:
    print("Compreso")
else:
    print("Non compreso")

if 5 <= len(b) <= 8:
    print("Compreso")
else:
    print("Non compreso")

if 5 <= len(c) <= 8:
    print("Compreso")
else:
    print("Non compreso")

if 5 <= len(d) <= 8:
    print("Compreso")
else:
    print("Non compreso")

"""un utente inserisce tre parole e il programma produce in output la prima in maiuscolo, la seconda in minuscolo e la terza con l'iniziale maiuscola.
 Poi prende i primi tre caratteri di ognuna e li stampa a video"""

x=input("insersci la prima parola")
print(x.upper())
y=input("inserisci la seconda parola")
print(y.lower())
z=input("inserisci la terza parola")
print(z[0].upper() + z[1:].lower())
x[0].upper(), y[0].upper(), z[0].upper()

#Un utente inserisce tre parole e il programma stampa il prodotto delle lunghezze delle parole
x=input("insersci la prima parola")
y=input("inserisci la seconda parola")
z=input("inserisci la terza parola")
print(len(x), len(y), len(z))